import test from 'node:test';
import assert from 'node:assert/strict';
import { randomBytes } from 'node:crypto';
import { readFile, mkdir, mkdtemp, copyFile, rm } from 'node:fs/promises';
import path from 'node:path';
import { createGitHub, validateCatalogue } from '../lib/github.js';
import { issueSession, readSession, cookie, checkPassword, requireCSRF, limitLogin } from '../lib/admin-session.js';
import { createAdminHandler } from '../api/admin.js';
import { createPreview } from '../scripts/preview.js';
import { githubFixture } from './helpers/github-fixture.js';
const products=JSON.parse(await readFile('data/products.json','utf8'));
process.env.ADMIN_PASSWORD=randomBytes(24).toString('hex');
process.env.SESSION_SECRET=randomBytes(48).toString('hex');
process.env.GITHUB_TOKEN='test-placeholder-not-a-secret';
process.env.GITHUB_OWNER='test-owner';process.env.GITHUB_REPO='test-repo';process.env.GITHUB_BRANCH='main';process.env.GITHUB_PRODUCTS_PATH='data/products.json';
process.env.NODE_ENV='test';
const signedReq=value=>({headers:{cookie:'ayva.sid='+value}});
test('signed expiring sessions, rotation, secure cookies and password comparison', async()=>{
  const issued=issueSession(true);
  assert.equal(readSession(signedReq(issued.value)).admin,true);
  assert.equal(readSession(signedReq(issued.value+'tampered')),null);
  assert.equal(readSession(signedReq(issued.value),Date.now()+3601000),null);
  assert.equal(readSession(signedReq('malformed')),null);
  assert.equal(await checkPassword(process.env.ADMIN_PASSWORD),true);
  assert.equal(await checkPassword('incorrect-password'),false);
  assert.equal(await checkPassword({password:process.env.ADMIN_PASSWORD}),false);
  const old=process.env.ADMIN_PASSWORD;process.env.ADMIN_PASSWORD+='rotated';
  assert.equal(readSession(signedReq(issued.value)),null);process.env.ADMIN_PASSWORD=old;
  process.env.NODE_ENV='production';assert.match(cookie(issued.value),/; Secure$/);process.env.NODE_ENV='test';
  assert.match(cookie('',true),/Max-Age=0/);
  const req={headers:{host:'localhost',origin:'http://localhost','x-csrf-token':issued.session.csrf}};
  requireCSRF(req,issued.session);
  assert.throws(()=>requireCSRF({...req,headers:{...req.headers,origin:'https://evil.example'}},issued.session),{status:403});
  assert.throws(()=>requireCSRF({...req,headers:{...req.headers,'sec-fetch-site':'cross-site'}},issued.session),{status:403});
  const login={headers:{},socket:{remoteAddress:'rate-limit-test'}};
  for(let i=0;i<10;i++)limitLogin(login,100000);
  assert.throws(()=>limitLogin(login,100001),{status:429});
  limitLogin(login,100000+16*60*1000);
});
test('GitHub configuration and upstream errors fail safely without leaking secrets',async()=>{
  let calls=0;
  const github=createGitHub(async()=>{calls++;throw new Error('upstream confidential error');});
  const token=process.env.GITHUB_TOKEN;delete process.env.GITHUB_TOKEN;
  await assert.rejects(github.read(),{status:503,code:'GITHUB_CONFIG'});assert.equal(calls,0);
  process.env.GITHUB_TOKEN=token;
  await assert.rejects(github.read(),{status:502,code:'GITHUB_UNAVAILABLE'});
  for(const [status,expected] of [[401,503],[403,503],[404,404],[409,409],[422,409],[429,503],[500,502]]) {
    const client=createGitHub(async()=>new Response('confidential upstream body',{status}));
    await assert.rejects(client.read(),error=>error.status===expected&&!error.message.includes('confidential'));
  }
  await assert.rejects(createGitHub(async()=>new Response('not json')).read(),{code:'GITHUB_RESPONSE'});
  await assert.rejects(createGitHub(async()=>Response.json({encoding:'base64',sha:'abc',content:Buffer.from('{}').toString('base64')})).read(),{code:'CATALOGUE_INVALID'});
  assert.throws(()=>validateCatalogue([products[0],products[0]]),{code:'DUPLICATE'});
});
test('admin HTTP errors, login, durable CRUD, revisions and GitHub request contract',async()=>{
  await mkdir('.test-data',{recursive:true});
  const dir=await mkdtemp(path.resolve('.test-data','admin-'));
  await copyFile('data/products.json',path.join(dir,'products.json'));
  const fixture=await githubFixture(dir);
  const server=createPreview({adminHandler:createAdminHandler(fixture.github)});
  server.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));
  const base='http://127.0.0.1:'+server.address().port;
  process.env.SITE_URL=base;
  const send=(route,options={})=>fetch(base+route,{redirect:'manual',...options});
  try {
    assert.equal((await send('/api/admin/products')).status,401);
    assert.equal((await send('/admin')).headers.get('location'),'/admin/login');
    const password=process.env.ADMIN_PASSWORD;delete process.env.ADMIN_PASSWORD;
    assert.equal((await send('/admin/login')).status,200);
    assert.equal((await send('/api/admin/login',{method:'POST'})).status,503);
    process.env.ADMIN_PASSWORD=password;
    const anonymous=issueSession();
    const loginHeaders={'content-type':'application/json',cookie:'ayva.sid='+anonymous.value,'x-csrf-token':anonymous.session.csrf};
    assert.equal((await send('/api/admin/login',{method:'POST',headers:loginHeaders,body:JSON.stringify({password:'wrong'})})).status,401);
    const login=await send('/api/admin/login',{method:'POST',headers:loginHeaders,body:JSON.stringify({password})});
    assert.equal(login.status,303);
    const sessionCookie=login.headers.get('set-cookie').split(';')[0];
    const session=readSession({headers:{cookie:sessionCookie}});
    const headers={'content-type':'application/json',cookie:sessionCookie,'x-csrf-token':session.csrf};
    const configuredToken=process.env.GITHUB_TOKEN;delete process.env.GITHUB_TOKEN;
    const unavailable=await send('/api/admin/products',{headers});assert.equal(unavailable.status,503);
    const safeError=await unavailable.text();assert.ok(!safeError.includes(password));assert.ok(!safeError.includes(configuredToken));
    process.env.GITHUB_TOKEN=configuredToken;
    const mutate=(route,method,data)=>send(route,{method,headers,body:JSON.stringify(data)});
    assert.equal((await send('/api/admin/products',{method:'PATCH',headers})).status,405);
    assert.equal((await send('/api/admin/products/absent',{headers})).status,404);
    assert.equal((await send('/api/admin/products',{method:'POST',headers,body:'{'})).status,400);
    assert.equal((await send('/api/admin/products',{method:'POST',headers,body:JSON.stringify({padding:'x'.repeat(3*1024*1024)})})).status,413);
    let current=await (await send('/api/admin/products',{headers})).json();
    const product={...structuredClone(products[0]),id:'manual-unit-test',slug:'manual-unit-test',status:'draft',images:[]};
    const created=await mutate('/api/admin/products','POST',{product,revision:current.revision});assert.equal(created.status,201);
    let revision=(await created.json()).revision;
    assert.equal((await mutate('/api/admin/products','POST',{product,revision})).status,409);
    assert.equal((await mutate('/api/admin/products/'+product.id,'PUT',{product,revision:'outdated'})).status,409);
    product.price+=5;product.description.ru='Проверка сохранения';product.properties=[{name:'Test',value:'Value'}];product.category.az='Test category';
    const updated=await mutate('/api/admin/products/'+product.id,'PUT',{product,revision});assert.equal(updated.status,200);revision=(await updated.json()).revision;
    // A fresh client reads the persisted contents, not an in-memory admin response.
    const reloaded=await (await githubFixture(dir)).github.read();
    const saved=reloaded.products.find(p=>p.id===product.id);
    assert.equal(saved.price,product.price);assert.deepEqual(saved.properties,product.properties);assert.equal(saved.category.az,product.category.az);assert.equal(saved.description.ru,product.description.ru);assert.equal(saved.sourceId,undefined);
    const missing=structuredClone(product);missing.images=structuredClone(products[0].images);missing.images[0].src='/media/missing.webp';
    assert.equal((await mutate('/api/admin/products/'+product.id,'PUT',{product:missing,revision})).status,400);
    assert.equal((await mutate('/api/admin/products/'+product.id,'DELETE',{revision})).status,200);
    current=await (await send('/api/admin/products',{headers})).json();assert.equal(current.products.length,products.length);
    assert.deepEqual(current.products,validateCatalogue(products));
    assert.equal((await mutate('/api/admin/logout','POST',{})).status,303);
    assert.equal(fixture.calls.filter(c=>c.endpoint==='contents/data/products.json'&&c.method==='PUT').length,3);
  } finally {delete process.env.SITE_URL;await new Promise(resolve=>server.close(resolve));await rm(dir,{recursive:true,force:true});}
});
